---
- name: Installing a Webserver
  hosts: web
  tasks:
  - name: Install HTTP Webserver
    yum:
      name: httpd
      state: present
  - name: Start Webserver
    service:
      name: httpd
      state: started
  - name: Create index.html file
    file:
      path: "/var/www/html/index.html"
      state: touch
  - name: Test html page
    copy:
      content: "Welcome to git"
      dest: /var/www/html/index.html
  - name: Enable Firewalld
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

...
